apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-bff
  template:
    metadata:
      labels:
        app: demo-bff
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: demo-bff
        image: spring-boot-hpa
        imagePullPolicy: IfNotPresent
        env:
        - name: WS_BE
          value: "http://localhost:8085/api/farmacias-be/farmaciasturno"
        - name: WS_BE_TIMEOUT
          value: "25000"
        ports:
          - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          httpGet:
            path: /healthcheck
            port: 8080
        resources:
          limits:
            memory: 256Mi
