# [Services]
apiVersion: v1
kind: Service
metadata:
  name: demo-be
spec:
  ports:
  - port: 8081
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: demo-be
    tier: backend
  type: NodePort

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-be
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-be
        tier: backend
    spec:
      containers:
      # [APP]
      - name: payment-be
        image: gcr.io/demoCluster/demo-be:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080